version: "3"
services:
  db:
    image: postgres:14
    restart: always
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=grape
      - POSTGRES_USER=grape
      - POSTGRES_DB=grape_schools
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./grape-db-data:/var/lib/postgresql/data/pgdata
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

volumes:
  grape-db-data: