"""Create users table

Revision ID: c3b25aa0420e
Revises: 67f2cf2116f6
Create Date: 2023-03-12 15:41:50.769151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b25aa0420e'
down_revision = '67f2cf2116f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
