"""Fixing User Student Relationship

Revision ID: d39af4278ae5
Revises: 321ca15092f2
Create Date: 2023-03-12 16:22:23.975337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39af4278ae5'
down_revision = '321ca15092f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_student_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_student_id_fkey', 'user', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
