"""Created and Updated at to models.

Revision ID: ff4c084f18c5
Revises: 94da84a16586
Create Date: 2023-03-12 17:42:04.672782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4c084f18c5'
down_revision = '94da84a16586'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('created_at', sa.DateTime(timezone=True), server_default='2023-03-12T17:42:04.390695', nullable=True))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(timezone=True), server_default='2023-03-12T17:42:04.390744', nullable=True))
    op.add_column('student', sa.Column('created_at', sa.DateTime(timezone=True), server_default='2023-03-12T17:42:04.387328', nullable=True))
    op.add_column('student', sa.Column('updated_at', sa.DateTime(timezone=True), server_default='2023-03-12T17:42:04.387361', nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default='2023-03-12T17:42:04.380284', nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(timezone=True), server_default='2023-03-12T17:42:04.380345', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('student', 'updated_at')
    op.drop_column('student', 'created_at')
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'created_at')
    # ### end Alembic commands ###
